[package]
name = "gpt"
version = "0.4.0"
description = "A pure-Rust library to work with GPT partition tables."
documentation = "https://docs.rs/gpt"
authors = ["Chris Ober <obercgit@gmail.com>", "Chris Holcombe <xfactor973@gmail.com>", "Luca Bruno <lucab@debian.org>"]
license = "MIT"
homepage = "https://github.com/Quyzi/gpt"
edition = "2018"

[dependencies]
bitflags = "~1.0"
byteorder = "~1.3"
crc = "~1.8"
log = "~0.4"
uuid = { version = "~0.7", features = ["v4"] }

[dev-dependencies]
simplelog = "~0.5"
tempfile = "~3.0"
